<?php

	$returnData = array();
	$returnData[] = array('title' => '4 checkboxes (vertical)', 'description' => 'Vertical arrangement of 4 checkboxes (multiple selections possible)', 'content' => '<p>[@CB GROUP="variableName" VALUE="value1"] [@LB]answer 1[@/LB]<br>[@CB VALUE="value2"] [@LB]answer 2[@/LB]<br>[@CB VALUE="value3"] [@LB]answer 3[@/LB]<br>[@CB VALUE="value4"] [@LB]answer 4[@/LB]</p>');
	$returnData[] = array('title' => '4 radio buttons (vertical)', 'description' => 'Vertical arrangement of 4 radio buttons (single selection possible)', 'content' => '<p>[@RB GROUP="variableName" VALUE="value1"] [@LB]answer 1[@/LB]<br>[@RB VALUE="value2"] [@LB]answer 2[@/LB]<br>[@RB VALUE="value3"] [@LB]answer 3[@/LB]<br>[@RB VALUE="value4"] [@LB]answer 4[@/LB]</p>');
	$returnData[] = array('title' => 'Dropdown field', 'description' => 'Dropdown field (single selection possible)', 'content' => '<p>Please make your choice: [@DD ID="variableName" OPTIONS="a good choice|a better choice even|yet another choice|you get the idea"@]</p>');
	//	$returnData[] = array('title' => 'Likert', 'description' => 'Likert scale (radio button grid with 5columns and 4 rows)', 'content' => '<table style="width: 100%;" border="0"><tbody><tr><td>&nbsp;</td><td style="width: 15%; text-align: center;">not at all</td><td style="width: 15%; text-align: center;">rather not</td><td style="width: 15%; text-align: center;">rather yes</td><td style="width: 15%; text-align: center;">very much so</td><td style="width: 15%; text-align: center;">don\'t know</td></tr><tr><td>question 1</td><td style="text-align: center;">[@RB]</td><td style="text-align: center;">[@RB]</td><td style="text-align: center;">[@RB]</td><td style="text-align: center;">[@RB]</td><td style="text-align: center;">[@RB]</td></tr><tr><td>question 2</td><td style="text-align: center;">[@RB NG]</td><td style="text-align: center;">[@RB]</td><td style="text-align: center;">[@RB]</td><td style="text-align: center;">[@RB]</td><td style="text-align: center;">[@RB]</td></tr><tr><td>question 3</td><td style="text-align: center;">[@RB NG]</td><td style="text-align: center;">[@RB]</td><td style="text-align: center;">[@RB]</td><td style="text-align: center;">[@RB]</td><td style="text-align: center;">[@RB]</td></tr><tr><td>question 4</td><td style="text-align: center;">[@RB NG]</td><td style="text-align: center;">[@RB]</td><td style="text-align: center;">[@RB]</td><td style="text-align: center;">[@RB]</td><td style="text-align: center;">[@RB]</td></tr></tbody></table>');
	//	$returnData[] = array('title' => 'Slider', 'description' => 'Horizontal slider', 'content' => '<p>In the following slider we have a precision of 0.1:</p><p>[@SLIDER MIN="-5" MAX="5" VALUE="0" STEP="0.1"@]</p>');
	$returnData[] = array('title' => 'Text area', 'description' => 'Open text entry (multiple lines)', 'content' => '<p>Please enter your comment:</p><p>[@TA ID="variableName" WIDTH="400" HEIGHT="200"@]</p>');
	$returnData[] = array('title' => 'Text field', 'description' => 'Open text entry (single line)', 'content' => '<p>Please enter your answer: [@TF ID="variableName" WIDTH="100"@]</p>');
	$returnData[] = array('title' => 'Slikert', 'description' => 'A Likert scale in form of a slider', 'content' => '<p>[@SLIKERT ID="opinion" MINLABEL="completely disagree" CENTERLABEL="neutral" MAXLABEL="completely agree" MIN="-2" MAX="2" @]</p>');
	$returnData[] = array('title' => 'Item Timer', 'description' => 'Insert a time for one item or a block of items', 'content' => '[@TIMER TIMEOUT="15" ID="Block001"]');
	$returnData[] = array('title' => 'Finish Button', 'description' => 'Button to close the test', 'content' => '[@BUTTON NAME="Close test" FUNCTION="endTest();"@]');
	// 	$returnData[] = array('title' => 'Drag and drop right/wrong', 'description' => 'Example item to sort draggables into 2 categories (right/wrong)', 'content' => '<table style="border: 1px solid black;"><tbody><tr><td style="background-color: #eeeeee;"><strong>&nbsp;Left</strong><div>[@DZ ID="dz_left" MAX="4" STYLE="position: relative; width: 328px; height: 224px; margin: 3px 0; background-color: none;" PADDING="5"@]</div></td><td style="background-color: #ffffff;">&nbsp;<b>Center</b><div>[@DZ ID="stock" MAX="4" STYLE="position: relative; width: 328px; height: 224px; background-color: none; border: none;" PADDING="5"@]</div></td><td style="background-color: #eeeeee;"><strong>&nbsp;Right</strong><div>[@DZ ID="dz_right" MAX="4" STYLE="position: relative; width: 328px; height: 224px; margin: 3px 0; background-color: none;" PADDING="5"@]</div></td></tr></tbody></table><p>[@DG ID="dg01" PARENT="stock" STYLE="width: 312px; height: 44px; border: 1px solid black; padding: 2px; background-color: #E5F2F7;" VALUE="1" LABEL="label1"@]</p> <p>[@DG ID="dg02" PARENT="stock" STYLE="width: 312px; height: 44px; border: 1px solid black; padding: 2px; background-color: #E5F2F7;" VALUE="2" LABEL="label2"@]</p> <p>[@DG ID="dg03" PARENT="stock" STYLE="width: 312px; height: 44px; border: 1px solid black; padding: 2px; background-color: #E5F2F7;" VALUE="3" LABEL="label3"@]</p><p>[@DG ID="dg04" PARENT="stock" STYLE="width: 312px; height: 44px; border: 1px solid black; padding: 2px; background-color: #E5F2F7;" VALUE="4" LABEL="label4"@]</p>');
	// 	$returnData[] = array('title' => 'Drag and drop sort item', 'description' => 'Example item where draggables need to be brought into the right order', 'content' => '<table><tbody><tr><td><div style="line-height: 31px;">1.</div><div style="line-height: 31px;">2.</div><div style="line-height: 31px;">3.</div><div style="line-height: 31px;">4.</div><div style="line-height: 31px;">5.</div><div style="line-height: 31px;">6.</div></td><td>[@DZ ID="dz01" MAX="6" STYLE="position: relative; width: 560px; height: 190px; border: 1px solid black; background-color: #eeeeee" ONDROP="insert" PADDING="5" @]</td></tr></tbody></table><div><p>[@DZ ID="stock" MAX="6" STYLE="position: relative; width: 560px; height: 190px; border: 1px solid black;" PADDING="5" @]</p><p>[@DG ID="dg01" PARENT="stock" STYLE="width: 546px; height: 20px; border: 1px solid black; padding: 2px; background-color: #E5F2F7;" VALUE="1" LABEL="label1"@]</p><p>[@DG ID="dg02" PARENT="stock" STYLE="width: 546px; height: 20px; border: 1px solid black; padding: 2px; background-color: #E5F2F7;" VALUE="2" LABEL="label2"@]</p><p>[@DG ID="dg03" PARENT="stock" STYLE="width: 546px; height: 20px; border: 1px solid black; padding: 2px; background-color: #E5F2F7;" VALUE="3" LABEL="label3"@]</p><p>[@DG ID="dg04" PARENT="stock" STYLE="width: 546px; height: 20px; border: 1px solid black; padding: 2px; background-color: #E5F2F7;" VALUE="4" LABEL="label4"@]</p><p>[@DG ID="dg05" PARENT="stock" STYLE="width: 546px; height: 20px; border: 1px solid black; padding: 2px; background-color: #E5F2F7;" VALUE="5" LABEL="label5"@]</p><p>[@DG ID="dg06" PARENT="stock" STYLE="width: 546px; height: 20px; border: 1px solid black; padding: 2px; background-color: #E5F2F7;" VALUE="6" LABEL="label6"@]</p></div>');

	// $returnData[] = array('title' => '', 'description' => '', 'content' => '');


	header('Cache-Control: no-cache, must-revalidate');
	header('Content-type: application/json; charset=UTF-8');
	echo json_encode($returnData);
